### ISSUE TITLE
Article view in mobile is obstructed by large nav bar

### ISSUE THREAD

**Issue by radu-matei** [deislabs/deislabs.io#10]
![771FD4A9-F7A0-41D2-8FEC-7B118457FE1A](https://user-images.githubusercontent.com/13103165/64217903-f96d1480-cec7-11e9-8663-a7c588686ef0.png)

**Comment by flynnduism** [comment]
This was changed in #48, now [Headroom.js](https://wicky.nillia.ms/headroom.js/) hides the menu as you scroll down the page.
