### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by radu-matei** [deislabs/deislabs.io#53]
There have been a couple of requests already for an RSS feed for the blog.
I do have an RSS feed for a Hugo static site that I could port (https://github.com/radu-matei/radu-matei.github.io/blob/content/themes/kiss/layouts/index.rss.xml), but I am by no means an expert here, so I would leave this to someone with more experience.

cc @flynnduism

**Comment by carolynvs** [comment]
I just realized that Porter's theme also doesn't generate an rss feed! 🤦‍♀️

**Comment by flynnduism** [comment]
Good idea Radu. Currently the site is generating [the feed](https://deislabs.io/index.xml), but it's not referenced in the page `head`. Same with Porter which is [here](https://porter.sh/index.xml). I'll update the site to make sure it's linked:

`<link href="https://deislabs.io/index.xml" rel="alternate" type="application/rss+xml" />`

**Comment by carolynvs** [comment]
For both sites (this and porter) the rss feed includes page updates in addition to blog posts. Can we change it to only provide rss for the blog portion?
